import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation } from "@tanstack/react-query";
import { motion, useReducedMotion } from "framer-motion";
import { Send } from "lucide-react";
import { useForm } from "react-hook-form";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { z } from "zod";
import { errorMessage } from "../api/client";
import { aiApi } from "../api/resources";
import { AnimatedNumber, AnalysisPulse, MotionTableBody, MotionTableRow, StreamingText, easeOutExpo } from "../components/motion";
import { ChartTooltip, FormError, PageHeader, TableShell } from "../components/ui";
import { currency, integer } from "../lib/format";
import { chartTheme } from "../lib/theme";
import type { AiExecutionResult, CategoryPerformance, ReturnAnalytics, SalesSummary, SalesTrend, TopProducts } from "../types/api";

const schema = z.object({ question: z.string().trim().min(1, "Sorunuzu yazın.").max(2000, "Soru en fazla 2000 karakter olabilir.") });
type Values = z.infer<typeof schema>;
const suggestions = ["Bu ay satışlarımız nasıl?", "Son 3 ayın aylık satış trendini göster.", "Bu yıl gelire göre en çok satan 5 ürün hangileri?", "Son 30 gündeki iadeleri analiz et."];

function Metric({ label, value, formatter }: { label: string; value: number; formatter: (value: number) => string }) { return <motion.div className="ai-metric" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><p className="eyebrow">{label}</p><p><AnimatedNumber value={value} format={formatter} /></p></motion.div>; }

function CompletedData({ result }: { result: AiExecutionResult }) {
  const data = result.data; const reduced = useReducedMotion(); if (!data) return null;
  if ("orderCount" in data && "averageOrderValue" in data) { const summary = data as SalesSummary; return <div className="grid gap-3 sm:grid-cols-4"><Metric label="Toplam gelir" value={summary.totalRevenue} formatter={(value) => currency.format(value)} /><Metric label="Sipariş" value={summary.orderCount} formatter={(value) => integer.format(Math.round(value))} /><Metric label="Satılan adet" value={summary.unitsSold} formatter={(value) => integer.format(Math.round(value))} /><Metric label="Ortalama sipariş" value={summary.averageOrderValue} formatter={(value) => currency.format(value)} /></div>; }
  if ("granularity" in data) { const trend = data as SalesTrend; return <div className="h-[310px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend.revenue}><defs><linearGradient id="aiFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={chartTheme.violet} stopOpacity={.22} /><stop offset="1" stopColor={chartTheme.violet} stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke={chartTheme.grid} vertical={false} /><XAxis dataKey="label" stroke={chartTheme.axis} tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis stroke={chartTheme.axis} tick={{ fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip content={<ChartTooltip valueFormatter={(value) => currency.format(value)} />} /><Area dataKey="value" name="Gelir" stroke={chartTheme.violet} strokeWidth={2.5} fill="url(#aiFill)" activeDot={{ r: 5, fill: chartTheme.primary, stroke: chartTheme.surface, strokeWidth: 3 }} isAnimationActive={!reduced} animationDuration={900} /></AreaChart></ResponsiveContainer></div>; }
  if ("metric" in data) { const products = data as TopProducts; return products.items.length ? <TableShell><table className="data-table"><thead><tr><th>#</th><th>Ürün</th><th>Adet</th><th>Gelir</th></tr></thead><MotionTableBody>{products.items.map((item) => <MotionTableRow key={item.productId}><td>{item.rank}</td><td><p className="table-item-title">{item.name}</p><p className="table-meta">{item.sku}</p></td><td>{item.quantity}</td><td>{currency.format(item.revenue)}</td></MotionTableRow>)}</MotionTableBody></table></TableShell> : null; }
  if ("reasons" in data) { const returns = data as ReturnAnalytics; return <div className="grid gap-3 sm:grid-cols-3"><Metric label="İade kaydı" value={returns.returnRecordCount} formatter={(value) => integer.format(Math.round(value))} /><Metric label="İade edilen" value={returns.returnedQuantity} formatter={(value) => `${integer.format(Math.round(value))} adet`} /><Metric label="İade tutarı" value={returns.totalReturnAmount} formatter={(value) => currency.format(value)} /></div>; }
  const categories = data as CategoryPerformance; return categories.items.length ? <TableShell><table className="data-table"><thead><tr><th>#</th><th>Kategori</th><th>Gelir</th><th>Pay</th></tr></thead><MotionTableBody>{categories.items.map((item) => <MotionTableRow key={item.categoryId}><td>{item.rank}</td><td className="table-item-title">{item.name}</td><td>{currency.format(item.revenue)}</td><td>%{item.revenueSharePercentage.toFixed(2)}</td></MotionTableRow>)}</MotionTableBody></table></TableShell> : null;
}

export function AiPage() {
  const reduced = useReducedMotion(); const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { question: "" } });
  const mutation = useMutation({ mutationFn: (values: Values) => aiApi.query(values.question), onError: (error) => toast.error(errorMessage(error)) });
  const result = mutation.data; const ask = (question: string) => { form.setValue("question", question, { shouldValidate: true }); mutation.mutate({ question }); };
  return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Doğal dil çalışma alanı" title="Veriye Sor" description="Satış verinizi gündelik Türkçeyle keşfedin. QueryPilot soruyu yapılandırır, uygun analizi çalıştırır ve sonucu açıklanabilir biçimde sunar." />
    <section className="ai-studio"><div className="ai-composer"><div className="ai-composer-head"><div><p className="eyebrow">Soru alanı</p><h2>Verinizde neyi görmek istiyorsunuz?</h2></div></div><form className="mt-5" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><div className="ai-input-wrap"><textarea className="textarea min-h-32 resize-y pr-16 text-sm leading-7" placeholder="Örn. Son 3 ayın aylık satış trendini göster." {...form.register("question")} /><motion.button className="ai-send" type="submit" aria-label="Soruyu gönder" disabled={mutation.isPending} whileHover={reduced ? undefined : { scale: 1.05 }} whileTap={reduced ? undefined : { scale: .92 }}><Send size={17} /></motion.button></div><FormError message={form.formState.errors.question?.message} /></form><div className="mt-4 flex flex-wrap gap-2">{suggestions.map((suggestion, index) => <motion.button className="suggestion" type="button" key={suggestion} onClick={() => ask(suggestion)} initial={reduced ? false : { opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .12 + index * .05 }}>{suggestion}</motion.button>)}</div></div>
      <div className="ai-response">{!result && !mutation.isPending && <motion.div className="ai-idle" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><p>İlk sorunuz için hazır</p><span>Satış özeti, trend, lider ürün, kategori ve iade analizleri desteklenir.</span></motion.div>}{mutation.isPending && <motion.div className="ai-thinking" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><AnalysisPulse /><div><strong>Analiz yolu kuruluyor</strong><motion.p animate={reduced ? undefined : { opacity: [.45, 1, .45] }} transition={{ duration: 1.4, repeat: Infinity }}>Soru yorumlanıyor, veri aralığı doğrulanıyor, sonuç hazırlanıyor</motion.p></div></motion.div>}
        {result?.status === "Completed" && <motion.div className="space-y-5" initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45, ease: easeOutExpo }}><div className="ai-answer"><div><p className="eyebrow">Analiz tamamlandı</p>{result.explanation?.status === "Available" && result.explanation.text && <StreamingText>{result.explanation.text}</StreamingText>}{result.warning && <p className="warning-text mt-2 text-[10px]">{result.warning}</p>}</div></div>{result.intent && <div className="flex flex-wrap gap-2"><span className="intent-chip">{result.intent.analysis}</span><span className="intent-chip">{new Date(result.intent.fromUtc).toLocaleDateString("tr-TR")} - {new Date(result.intent.toUtc).toLocaleDateString("tr-TR")}</span>{result.intent.metric && <span className="intent-chip">{result.intent.metric}</span>}{result.intent.granularity && <span className="intent-chip">{result.intent.granularity}</span>}</div>}<CompletedData result={result} /><p className="ai-footnote">Sonuç, backend analitiğinin döndürdüğü güncel veriden üretilmiştir.</p></motion.div>}
        {result?.status === "NeedsClarification" && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><div><p className="eyebrow">Netleştirelim</p><h2 className="response-title">Biraz daha bilgi gerekli</h2><p className="response-copy">{result.message}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{result.clarification?.requiredFields.map((field) => <div className="clarification-card" key={field.field}><p>{field.question}</p>{field.allowedValues.length > 0 && <span>Seçenekler: {field.allowedValues.join(", ")}</span>}</div>)}</div><p className="caption mt-4">{result.clarification?.retryInstruction}</p></motion.div>}
        {result?.status === "Unsupported" && <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><div><p className="eyebrow">Kapsam dışında</p><h2 className="response-title">Başka bir açı deneyin</h2><p className="response-copy">Aşağıdaki desteklenen örneklerden biriyle devam edebilirsiniz.</p></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{result.unsupported?.exampleQuestions.map((question) => <button className="suggestion text-left" key={question} onClick={() => ask(question)}>{question}</button>)}</div></motion.div>}
      </div>
    </section>
  </div>;
}
