import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Mail, MapPin, Pencil, Plus, Power, Search } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { errorMessage } from "../api/client";
import { customersApi, type CustomerInput } from "../api/resources";
import { EmptyState, ErrorState, LoadingState } from "../components/feedback";
import { MotionTableBody, MotionTableRow } from "../components/motion";
import { ActiveBadge, CollectionSummary, FormError, Modal, PageHeader, Pagination, SubmitButton, TableShell } from "../components/ui";
import { useDebouncedValue } from "../hooks/useDebouncedValue";
import type { Customer } from "../types/api";

const schema = z.object({ name: z.string().trim().min(1, "Müşteri adı zorunludur.").max(150), email: z.email("Geçerli bir e-posta girin.").max(320), city: z.string().trim().min(1, "Şehir zorunludur.").max(100), isActive: z.boolean() });

export function CustomersPage() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const deferredSearch = useDebouncedValue(search); const [city, setCity] = useState(""); const deferredCity = useDebouncedValue(city); const [activeFilter, setActiveFilter] = useState(""); const [editing, setEditing] = useState<Customer | null | undefined>(undefined);
  const query = useQuery({ queryKey: ["customers", page, deferredSearch, deferredCity, activeFilter], queryFn: () => customersApi.list({ page, pageSize: 20, search: deferredSearch || undefined, city: deferredCity || undefined, isActive: activeFilter === "" ? undefined : activeFilter === "true" }), placeholderData: (previous) => previous });
  const form = useForm<CustomerInput>({ resolver: zodResolver(schema), defaultValues: { name: "", email: "", city: "", isActive: true } });
  const close = () => { setEditing(undefined); form.reset(); }; const open = (item: Customer | null) => { form.reset(item ? { name: item.name, email: item.email, city: item.city, isActive: item.isActive } : { name: "", email: "", city: "", isActive: true }); setEditing(item); };
  const save = useMutation({ mutationFn: (values: CustomerInput) => editing ? customersApi.update(editing.id, values) : customersApi.create(values), onSuccess: async () => { toast.success(editing ? "Müşteri güncellendi." : "Müşteri oluşturuldu."); close(); await client.invalidateQueries({ queryKey: ["customers"] }); }, onError: (error) => toast.error(errorMessage(error)) });
  const deactivate = useMutation({ mutationFn: customersApi.deactivate, onSuccess: async () => { toast.success("Müşteri pasifleştirildi."); await client.invalidateQueries({ queryKey: ["customers"] }); }, onError: (error) => toast.error(errorMessage(error)) });

  return <div className="mx-auto max-w-[1400px]"><PageHeader eyebrow="Müşteri yönetimi" title="Müşteriler" description="Müşteri iletişim bilgilerini yönetin; sipariş geçmişi bulunan kayıtlar pasifleştirildiğinde korunur." action={<button className="btn btn-primary" onClick={() => open(null)}><Plus size={16} />Yeni müşteri</button>} />
    <div className="filter-bar md:grid-cols-[1fr_220px_170px]"><label className="relative"><Search className="absolute left-3 top-3 text-muted" size={16} /><input className="input pl-9" placeholder="Ad veya e-posta ara" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></label><input className="input" aria-label="Şehir filtresi" placeholder="Şehir filtresi" value={city} onChange={(event) => { setCity(event.target.value); setPage(1); }} /><select className="select" aria-label="Durum filtresi" value={activeFilter} onChange={(event) => { setActiveFilter(event.target.value); setPage(1); }}><option value="">Tüm durumlar</option><option value="true">Aktif</option><option value="false">Pasif</option></select></div>
    {query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={errorMessage(query.error)} onRetry={() => void query.refetch()} /> : !query.data?.items.length ? <EmptyState title="Müşteri bulunamadı" description="Arama ölçütlerini değiştirin veya yeni bir müşteri ekleyin." /> : <><CollectionSummary items={[{ label: "Eşleşen müşteri", value: query.data.totalCount }, { label: "Bu sayfada aktif", value: query.data.items.filter((item) => item.isActive).length, tone: "sage" }, { label: "Görünen şehir", value: new Set(query.data.items.map((item) => item.city)).size, tone: "lilac", detail: "Bu sayfadaki kayıtlar" }]} /><TableShell busy={query.isFetching}><table className="data-table"><thead><tr><th>Müşteri</th><th>İletişim</th><th>Şehir</th><th>Durum</th><th className="text-right!">İşlem</th></tr></thead><MotionTableBody refreshKey={`${page}-${deferredSearch}-${deferredCity}-${activeFilter}`}>{query.data.items.map((item) => <MotionTableRow key={item.id}><td><p className="table-item-title">{item.name}</p><p className="table-meta">#{item.id}</p></td><td><span className="inline-flex items-center gap-2"><Mail size={14} className="text-muted" />{item.email}</span></td><td><span className="inline-flex items-center gap-2"><MapPin size={14} className="text-muted" />{item.city}</span></td><td><ActiveBadge active={item.isActive} /></td><td><div className="flex justify-end gap-2"><button className="icon-btn" aria-label={`${item.name} müşterisini düzenle`} onClick={() => open(item)}><Pencil size={15} /></button>{item.isActive && <button className="icon-btn warning-text" aria-label={`${item.name} müşterisini pasifleştir`} onClick={() => { if (window.confirm(`${item.name} müşterisi pasifleştirilsin mi?`)) deactivate.mutate(item.id); }}><Power size={15} /></button>}</div></td></MotionTableRow>)}</MotionTableBody></table></TableShell><Pagination page={query.data.page} totalPages={query.data.totalPages} totalCount={query.data.totalCount} onPage={setPage} /></>}
    {editing !== undefined && <Modal title={editing ? "Müşteriyi düzenle" : "Yeni müşteri"} onClose={close}><form className="space-y-4" onSubmit={form.handleSubmit((values) => save.mutate(values))}><label className="field-label block">Ad soyad<input className="input mt-1" {...form.register("name")} /><FormError message={form.formState.errors.name?.message} /></label><label className="field-label block">E-posta<input className="input mt-1" type="email" {...form.register("email")} /><FormError message={form.formState.errors.email?.message} /></label><label className="field-label block">Şehir<input className="input mt-1" {...form.register("city")} /><FormError message={form.formState.errors.city?.message} /></label>{editing && <label className="form-check"><input className="checkbox" type="checkbox" {...form.register("isActive")} />Aktif müşteri</label>}<div className="flex justify-end gap-2 pt-2"><button className="btn btn-secondary" type="button" onClick={close}>Vazgeç</button><SubmitButton pending={save.isPending}>Kaydet</SubmitButton></div></form></Modal>}
  </div>;
}
