import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, MinusCircle, Plus } from "lucide-react";
import { useState } from "react";
import { useFieldArray, useForm, useWatch } from "react-hook-form";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { z } from "zod";
import { errorMessage } from "../api/client";
import { customersApi, ordersApi, productsApi } from "../api/resources";
import { ErrorState, LoadingState } from "../components/feedback";
import { AnimatedNumber, easeOutExpo } from "../components/motion";
import { FormError, PageHeader, SubmitButton } from "../components/ui";
import { useDebouncedValue } from "../hooks/useDebouncedValue";
import { currency } from "../lib/format";

const schema = z.object({ customerId: z.number().int().positive("Aktif bir müşteri seçin."), items: z.array(z.object({ productId: z.number().int().positive("Ürün seçin."), quantity: z.number().int().positive("Miktar en az 1 olmalıdır.") })).min(1, "En az bir sipariş kalemi ekleyin.") }).superRefine((value, context) => { const ids = value.items.map((item) => item.productId).filter(Boolean); if (new Set(ids).size !== ids.length) context.addIssue({ code: "custom", message: "Aynı ürün bir siparişte yalnız bir kez seçilebilir.", path: ["items"] }); });
type Values = z.infer<typeof schema>;

export function NewOrderPage() {
  const navigate = useNavigate(); const reduced = useReducedMotion(); const [customerSearch, setCustomerSearch] = useState(""); const [productSearch, setProductSearch] = useState(""); const customerQuery = useDebouncedValue(customerSearch); const productQuery = useDebouncedValue(productSearch);
  const customers = useQuery({ queryKey: ["customers", "order-options", customerQuery], queryFn: () => customersApi.list({ pageSize: 100, isActive: true, search: customerQuery || undefined }), placeholderData: (previous) => previous });
  const products = useQuery({ queryKey: ["products", "order-options", productQuery], queryFn: () => productsApi.list({ pageSize: 100, isActive: true, search: productQuery || undefined }), placeholderData: (previous) => previous });
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { customerId: 0, items: [{ productId: 0, quantity: 1 }] } }); const fields = useFieldArray({ control: form.control, name: "items" }); const selected = useWatch({ control: form.control, name: "items" });
  const mutation = useMutation({ mutationFn: ordersApi.create, onSuccess: (order) => { toast.success(`Sipariş #${order.id} oluşturuldu.`); void navigate(`/orders/${order.id}`); }, onError: (error) => toast.error(errorMessage(error)) });
  const estimate = selected.reduce((sum, item) => sum + (products.data?.items.find((product) => product.id === item.productId)?.unitPrice ?? 0) * (Number(item.quantity) || 0), 0);
  if (customers.isLoading || products.isLoading) return <LoadingState label="Sipariş seçenekleri hazırlanıyor" />;
  if (customers.isError || products.isError) return <ErrorState message={errorMessage(customers.error || products.error)} />;

  return <div className="mx-auto max-w-6xl"><PageHeader eyebrow="Sipariş oluşturucu" title="Yeni sipariş" description="Müşteriyi ve ürünleri seçin; kesin fiyat snapshot’ı ve toplam backend tarafından güvenle oluşturulsun." action={<Link className="btn btn-secondary" to="/orders"><ArrowLeft size={16} />Siparişlere dön</Link>} />
    <form className="grid gap-4 lg:grid-cols-[1fr_340px]" onSubmit={form.handleSubmit((values) => mutation.mutate(values))}><div className="space-y-4"><motion.section className="panel order-step p-5 sm:p-6" initial={reduced ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}><div className="step-heading"><div><p className="eyebrow">Müşteri</p><h2>Sipariş sahibini belirleyin</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="field-label block">Müşteri ara<input className="input mt-1" placeholder="Ad veya e-posta" value={customerSearch} onChange={(event) => setCustomerSearch(event.target.value)} /></label><label className="field-label block">Aktif müşteri<select className="select mt-1" {...form.register("customerId", { valueAsNumber: true })}><option value={0}>Müşteri seçin</option>{customers.data?.items.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} - {customer.email}</option>)}</select><FormError message={form.formState.errors.customerId?.message} /></label></div></motion.section>
      <motion.section className="panel order-step p-5 sm:p-6" initial={reduced ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }}><div className="flex items-center justify-between gap-4"><div className="step-heading"><div><p className="eyebrow">Ürünler</p><h2>Sipariş kalemlerini oluşturun</h2></div></div><button className="btn btn-secondary" type="button" onClick={() => fields.append({ productId: 0, quantity: 1 })}><Plus size={15} />Kalem ekle</button></div><label className="field-label mt-5 block">Ürün listesinde ara<input className="input mt-1" placeholder="Ürün adı veya SKU" value={productSearch} onChange={(event) => setProductSearch(event.target.value)} /></label><div className="mt-4 space-y-3"><AnimatePresence initial={false}>{fields.fields.map((field, index) => <motion.div className="order-line" key={field.id} layout initial={reduced ? false : { opacity: 0, height: 0, y: -8 }} animate={{ opacity: 1, height: "auto", y: 0 }} exit={{ opacity: 0, height: 0, scale: .97 }} transition={{ duration: reduced ? 0 : .28, ease: easeOutExpo }}><label className="field-label">Ürün<select className="select mt-1" {...form.register(`items.${index}.productId`, { valueAsNumber: true })}><option value={0}>Ürün seçin</option>{products.data?.items.map((product) => <option key={product.id} value={product.id}>{product.name} - {currency.format(product.unitPrice)}</option>)}</select><FormError message={form.formState.errors.items?.[index]?.productId?.message} /></label><label className="field-label">Miktar<input className="input mt-1" type="number" min="1" {...form.register(`items.${index}.quantity`, { valueAsNumber: true })} /><FormError message={form.formState.errors.items?.[index]?.quantity?.message} /></label><button className="icon-btn danger-action" type="button" aria-label={`${index + 1}. kalemi kaldır`} disabled={fields.fields.length === 1} onClick={() => fields.remove(index)}><MinusCircle size={17} /></button></motion.div>)}</AnimatePresence></div><FormError message={form.formState.errors.items?.root?.message || form.formState.errors.items?.message} /></motion.section></div>
      <motion.aside className="panel order-summary h-fit p-5 lg:sticky lg:top-24" initial={reduced ? false : { opacity: 0, x: 15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: .14, ease: easeOutExpo }}><p className="eyebrow">Sipariş özeti</p><div className="summary-row"><span>Kalem sayısı</span><strong>{fields.fields.length}</strong></div><div className="summary-row total"><span>Tahmini toplam</span><strong><AnimatedNumber value={estimate} format={(value) => currency.format(value)} /></strong></div><div className="summary-rule" /><p className="caption">Bu değer önizlemedir. Kaydedilen fiyat ve toplam, backend’deki güncel ürün fiyatlarından hesaplanır.</p><div className="mt-5 [&>button]:w-full"><SubmitButton pending={mutation.isPending}>Siparişi oluştur</SubmitButton></div><div className="backend-note">Yeni siparişler <strong>Pending</strong> oluşturulur. Mevcut API’de durum değiştirme işlemi bulunmuyor.</div></motion.aside></form>
  </div>;
}
