import { useQuery } from "@tanstack/react-query";
import { Eye, Plus, Search } from "lucide-react";
import { useState } from "react";
import { Link } from "react-router-dom";
import { errorMessage } from "../api/client";
import { ordersApi } from "../api/resources";
import { EmptyState, ErrorState, LoadingState } from "../components/feedback";
import { MotionTableBody, MotionTableRow } from "../components/motion";
import { CollectionSummary, OrderStatusBadge, PageHeader, Pagination, TableShell } from "../components/ui";
import { currency, formatDate, toUtcInclusiveEnd, toUtcStart } from "../lib/format";
import type { OrderStatus } from "../types/api";

export function OrdersPage() {
  const [page, setPage] = useState(1); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [status, setStatus] = useState<OrderStatus | "">(""); const [customerId, setCustomerId] = useState("");
  const query = useQuery({ queryKey: ["orders", page, from, to, status, customerId], queryFn: () => ordersApi.list({ page, pageSize: 20, from: from ? toUtcStart(from) : undefined, to: to ? toUtcInclusiveEnd(to) : undefined, status: status || undefined, customerId: customerId ? Number(customerId) : undefined }), placeholderData: (previous) => previous });
  return <div className="mx-auto max-w-[1400px]"><PageHeader eyebrow="Operasyon" title="Siparişler" description="Siparişleri tarihe, duruma ve müşteriye göre izleyin. Finansal toplamlar backend tarafından hesaplanır." action={<Link className="btn btn-primary" to="/orders/new"><Plus size={16} />Yeni sipariş</Link>} />
    <div className="filter-bar sm:grid-cols-2 xl:grid-cols-5"><label className="field-label">Başlangıç<input className="input mt-1" type="date" value={from} onChange={(event) => { setFrom(event.target.value); setPage(1); }} /></label><label className="field-label">Bitiş<input className="input mt-1" type="date" value={to} onChange={(event) => { setTo(event.target.value); setPage(1); }} /></label><label className="field-label">Durum<select className="select mt-1" value={status} onChange={(event) => { setStatus(event.target.value as OrderStatus | ""); setPage(1); }}><option value="">Tümü</option><option value="Pending">Bekliyor</option><option value="Completed">Tamamlandı</option><option value="Cancelled">İptal</option></select></label><label className="field-label">Müşteri ID<input className="input mt-1" type="number" min="1" placeholder="Örn. 42" value={customerId} onChange={(event) => { setCustomerId(event.target.value); setPage(1); }} /></label><div className="flex items-end"><button className="btn btn-secondary h-[42px] w-full" type="button" onClick={() => { setFrom(""); setTo(""); setStatus(""); setCustomerId(""); setPage(1); }}><Search size={15} />Filtreleri temizle</button></div></div>
    {query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={errorMessage(query.error)} onRetry={() => void query.refetch()} /> : !query.data?.items.length ? <EmptyState title="Sipariş bulunamadı" description="Tarih veya durum filtrelerini değiştirerek yeniden deneyin." /> : <><CollectionSummary items={[{ label: "Eşleşen sipariş", value: query.data.totalCount }, { label: "Görünen satış", value: currency.format(query.data.items.reduce((sum, item) => sum + item.totalAmount, 0)), tone: "sage", detail: "Bu sayfadaki kayıtlar" }, { label: "Toplam kalem", value: query.data.items.reduce((sum, item) => sum + item.itemCount, 0), tone: "lilac", detail: "Bu sayfadaki kayıtlar" }]} /><TableShell busy={query.isFetching}><table className="data-table"><thead><tr><th>Sipariş</th><th>Müşteri</th><th>Tarih</th><th>Kalem</th><th>Toplam</th><th>Durum</th><th /></tr></thead><MotionTableBody refreshKey={`${page}-${from}-${to}-${status}-${customerId}`}>{query.data.items.map((order) => <MotionTableRow key={order.id}><td className="table-item-title">#{order.id}</td><td>#{order.customerId}</td><td>{formatDate(order.orderDate)}</td><td>{order.itemCount}</td><td className="numeric-value">{currency.format(order.totalAmount)}</td><td><OrderStatusBadge status={order.status} /></td><td><Link className="icon-btn" aria-label={`${order.id} siparişini görüntüle`} to={`/orders/${order.id}`}><Eye size={15} /></Link></td></MotionTableRow>)}</MotionTableBody></table></TableShell><Pagination page={query.data.page} totalPages={query.data.totalPages} totalCount={query.data.totalCount} onPage={setPage} /></>}
  </div>;
}
