import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Pencil, Plus, Power, Search } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { errorMessage } from "../api/client";
import { categoriesApi, productsApi, type ProductInput } from "../api/resources";
import { EmptyState, ErrorState, LoadingState } from "../components/feedback";
import { MotionTableBody, MotionTableRow } from "../components/motion";
import { ActiveBadge, CollectionSummary, FormError, Modal, PageHeader, Pagination, SubmitButton, TableShell } from "../components/ui";
import { useDebouncedValue } from "../hooks/useDebouncedValue";
import { currency } from "../lib/format";
import type { Product } from "../types/api";

const schema = z.object({ name: z.string().trim().min(1, "Ürün adı zorunludur.").max(200), sku: z.string().trim().min(1, "SKU zorunludur.").max(64), categoryId: z.number().int().positive("Kategori seçin."), unitPrice: z.number().positive("Fiyat sıfırdan büyük olmalıdır."), isActive: z.boolean() });

export function ProductsPage() {
  const client = useQueryClient();
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const deferredSearch = useDebouncedValue(search); const [categoryId, setCategoryId] = useState(""); const [activeFilter, setActiveFilter] = useState(""); const [editing, setEditing] = useState<Product | null | undefined>(undefined);
  const categories = useQuery({ queryKey: ["categories", "options"], queryFn: () => categoriesApi.list({ pageSize: 100 }) });
  const query = useQuery({ queryKey: ["products", page, deferredSearch, categoryId, activeFilter], queryFn: () => productsApi.list({ page, pageSize: 20, search: deferredSearch || undefined, categoryId: categoryId ? Number(categoryId) : undefined, isActive: activeFilter === "" ? undefined : activeFilter === "true" }), placeholderData: (previous) => previous });
  const form = useForm<ProductInput>({ resolver: zodResolver(schema), defaultValues: { name: "", sku: "", categoryId: 0, unitPrice: 0, isActive: true } });
  const close = () => { setEditing(undefined); form.reset(); };
  const open = (item: Product | null) => { form.reset(item ? { name: item.name, sku: item.sku, categoryId: item.category.id, unitPrice: item.unitPrice, isActive: item.isActive } : { name: "", sku: "", categoryId: 0, unitPrice: 0, isActive: true }); setEditing(item); };
  const save = useMutation({ mutationFn: (values: ProductInput) => editing ? productsApi.update(editing.id, values) : productsApi.create(values), onSuccess: async () => { toast.success(editing ? "Ürün güncellendi." : "Ürün oluşturuldu."); close(); await client.invalidateQueries({ queryKey: ["products"] }); }, onError: (error) => toast.error(errorMessage(error)) });
  const deactivate = useMutation({ mutationFn: productsApi.deactivate, onSuccess: async () => { toast.success("Ürün pasifleştirildi."); await client.invalidateQueries({ queryKey: ["products"] }); }, onError: (error) => toast.error(errorMessage(error)) });

  return <div className="mx-auto max-w-[1400px]"><PageHeader eyebrow="Katalog" title="Ürünler" description="Ürünleri, SKU değerlerini, güncel liste fiyatlarını ve kategori ilişkilerini yönetin." action={<button className="btn btn-primary" onClick={() => open(null)}><Plus size={16} />Yeni ürün</button>} />
    <div className="filter-bar md:grid-cols-[1fr_220px_170px]"><label className="relative"><Search className="absolute left-3 top-3 text-muted" size={16} /><input className="input pl-9" placeholder="Ürün adı veya SKU ara" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></label><select className="select" aria-label="Kategori filtresi" value={categoryId} onChange={(event) => { setCategoryId(event.target.value); setPage(1); }}><option value="">Tüm kategoriler</option>{categories.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="select" aria-label="Durum filtresi" value={activeFilter} onChange={(event) => { setActiveFilter(event.target.value); setPage(1); }}><option value="">Tüm durumlar</option><option value="true">Aktif</option><option value="false">Pasif</option></select></div>
    {query.isLoading ? <LoadingState /> : query.isError ? <ErrorState message={errorMessage(query.error)} onRetry={() => void query.refetch()} /> : !query.data?.items.length ? <EmptyState title="Ürün bulunamadı" description="Arama ölçütlerini değiştirin veya yeni bir ürün oluşturun." /> : <><CollectionSummary items={[{ label: "Eşleşen ürün", value: query.data.totalCount }, { label: "Bu sayfada aktif", value: query.data.items.filter((item) => item.isActive).length, tone: "sage" }, { label: "Ortalama liste fiyatı", value: currency.format(query.data.items.reduce((sum, item) => sum + item.unitPrice, 0) / query.data.items.length), tone: "lilac", detail: "Bu sayfadaki kayıtlar" }]} /><TableShell busy={query.isFetching}><table className="data-table"><thead><tr><th>Ürün</th><th>Kategori</th><th>Fiyat</th><th>Durum</th><th className="text-right!">İşlem</th></tr></thead><MotionTableBody refreshKey={`${page}-${deferredSearch}-${categoryId}-${activeFilter}`}>{query.data.items.map((item) => <MotionTableRow key={item.id}><td><p className="table-item-title">{item.name}</p><p className="table-meta">{item.sku}</p></td><td>{item.category.name}</td><td className="numeric-value">{currency.format(item.unitPrice)}</td><td><ActiveBadge active={item.isActive} /></td><td><div className="flex justify-end gap-2"><button className="icon-btn" aria-label={`${item.name} ürününü düzenle`} onClick={() => open(item)}><Pencil size={15} /></button>{item.isActive && <button className="icon-btn warning-text" aria-label={`${item.name} ürününü pasifleştir`} onClick={() => { if (window.confirm(`${item.name} ürünü pasifleştirilsin mi?`)) deactivate.mutate(item.id); }}><Power size={15} /></button>}</div></td></MotionTableRow>)}</MotionTableBody></table></TableShell><Pagination page={query.data.page} totalPages={query.data.totalPages} totalCount={query.data.totalCount} onPage={setPage} /></>}
    {editing !== undefined && <Modal title={editing ? "Ürünü düzenle" : "Yeni ürün"} onClose={close}><form className="grid gap-4 sm:grid-cols-2" onSubmit={form.handleSubmit((values) => save.mutate(values))}><label className="field-label block sm:col-span-2">Ürün adı<input className="input mt-1" {...form.register("name")} /><FormError message={form.formState.errors.name?.message} /></label><label className="field-label block">SKU<input className="input mt-1" {...form.register("sku")} /><FormError message={form.formState.errors.sku?.message} /></label><label className="field-label block">Birim fiyat<input className="input mt-1" type="number" min="0.01" step="0.01" {...form.register("unitPrice", { valueAsNumber: true })} /><FormError message={form.formState.errors.unitPrice?.message} /></label><label className="field-label block sm:col-span-2">Kategori<select className="select mt-1" {...form.register("categoryId", { valueAsNumber: true })}><option value={0}>Kategori seçin</option>{categories.data?.items.map((item) => <option key={item.id} value={item.id}>{item.name}{!item.isActive ? " (pasif)" : ""}</option>)}</select><FormError message={form.formState.errors.categoryId?.message} /></label>{editing && <label className="form-check sm:col-span-2"><input className="checkbox" type="checkbox" {...form.register("isActive")} />Aktif ürün</label>}<div className="flex justify-end gap-2 pt-2 sm:col-span-2"><button className="btn btn-secondary" type="button" onClick={close}>Vazgeç</button><SubmitButton pending={save.isPending}>Kaydet</SubmitButton></div></form></Modal>}
  </div>;
}
